
server {
    listen 80;
    server_name _;
#
#    server_name meidanOmaDomain.fi;
#    return 301 https://$host$request_uri;
#}
#
#server {
#    listen 443 ssl http2;
#    server_name atm.domain.fi;
#
#    ssl_certificate /etc/letsencrypt/live/atm.domain.fi/fullchain.pem;
#    ssl_certificate_key /etc/letsencrypt/live/atm.domain.fi/privkey.pem;

    # Turvaotsakkeet
    add_header X-Content-Type-Options nosniff always;
    add_header X-Frame-Options SAMEORIGIN always;
    add_header Referrer-Policy no-referrer-when-downgrade always;
    add_header X-XSS-Protection "1; mode=block" always;

    # Vastaa juureen OK, jottei tuu 404
    location = / {
        return 200 'OK';
        add_header Content-Type text/plain;
    }

    # Health proxy API:n /health:iin (ei cachea koskaan)
    location /health {
        proxy_pass http://api:3000/health;
        proxy_http_version 1.1;

        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_connect_timeout 3s;
        proxy_read_timeout    10s;

        # Ei koskaan cachea /health:iä
        proxy_no_cache 1;
        proxy_cache_bypass 1;
        add_header Cache-Control "no-store" always;
    }

    # API (REST + WebSocket lisäominaisuus)
    location /api/ {
        # Dos/rate limit
        limit_req zone=api_limit burst=40 nodelay;

        # CORS
        add_header Access-Control-Allow-Origin * always;
        add_header Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS" always;
        add_header Access-Control-Allow-Headers "Authorization, Content-Type" always;

        # CORS-ennakkotarkastuspyyntö mm Postmania varten
        if ($request_method = OPTIONS) {
            return 204;
        }

        # WebSocket-tuki lisäominaisuudelle
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;

        # stripataan /api
        proxy_pass http://api:3000;
        proxy_http_version 1.1;

        # headerit taaksepäin
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # timeoutit nostettu websocketia varten
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;

        # Cache vain GET/HEAD
        proxy_cache         api_cache;
        proxy_cache_methods GET HEAD;
        proxy_cache_valid   200 1m;
        proxy_cache_valid   404 30s;

        # Ohjaa cachen ohitus metodin mukaan (mapattu http-kontekstissa 00_globals.conf:ssa)
        proxy_no_cache      $no_cache;
        proxy_cache_bypass  $no_cache;
    }
}
